#!/usr/bin/env bash
#PBS -N dyx_task1_regr
#PBS -l nodes=1:ppn=1
#PBS -l mem=64gb
#PBS -l walltime=120:00:00
#PBS -o /public3/home/off_dongyunxuan/dyx_G2P/logs/task1_ridge_elasticnet.pbs.out
#PBS -e /public3/home/off_dongyunxuan/dyx_G2P/logs/task1_ridge_elasticnet.pbs.err

set -euo pipefail
cd /public1/home/stu_gaoruiting/project/Ssin/HiFiasm/merge/2024-8-28/pop/Ai-input
bash programs/run_task1_ridge_elasticnet.sh
